### ISSUE TITLE
Personal Access Token

### ISSUE THREAD

**Issue by thjont** [marcaurele/gandi-2-terraform#73]
Hello,

I've found this project very useful, thank you for creating it.

Gandi have depreciated the use of the API key and replaced it with the Personal Access Token. https://docs.gandi.net/en/managing_an_organization/organizations/personal_access_token.html. In accounts that use SAML SSO for login, which mine does, the API key is already disabled. i.e. Personal Access Token is the only option for me.

The header format for PAT is `'authorization: Bearer 1234567890abcdefg1235467890'`. I've created a branch branch locally,where I've hacked the header and it's working. Below is what I've changed to use PAT for auth.

Line 29
```
        "X-Api-Key": os.getenv("GANDI_KEY"),
        "Authorization": f'Bearer {os.getenv("GANDI_KEY")}',
```
Line 50 
```
        headers={"authorization": f'Apikey {os.getenv("GANDI_KEY")}'},
        headers={"Authorization": f'Bearer {os.getenv("GANDI_KEY")}'},
```

Line 65
```
        headers={"authorization": f'Apikey {os.getenv("GANDI_KEY")}'},
        headers={"Authorization": f'Bearer {os.getenv("GANDI_KEY")}'},
```

Thanks

**Comment by marcaurele** [comment]
Hi @thjont !

That's right, I forgot to adapt the code. I will do push a change to modify that part of the code.
